version: '3.7'

services:
  app:
    build: .
    image: <%= name %>/<%= name %>
    container_name: <%= name %>
    restart: always
    volumes:
      - /app/node_modules

volumes:
  <%= name %>-web-volume:
